name: Build and Deploy to GCP Storage

on:
  push:
    branches:
      - ci_test

jobs:
    build:
        name: Build Image
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v3
              with:
                ref: ci_test
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 16.3
                cache: "npm"
            - run: npm install
            - name: Build
              run: npm run build
              env:
                CI: ""